# Étape 1 : build
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# Étape 2 : serveur statique
FROM nginx:alpine

# Copie le build dans Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copie une config nginx personnalisée (optionnel)
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
