
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app # signifie que tout changement dans VS Code est immédiatement visible dans le conteneur Docker
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev.frontend
    container_name: frontend
    volumes:
      - ./frontend:/app # signifie que tout changement dans VS Code est immédiatement visible dans le conteneur Docker
      - /app/node_modules  # évite les conflits de node_modules entre host et container
    ports:
      - "3000:3000"
    environment:
      # - NODE_ENV=production
      - NODE_ENV=development
      - VITE_PORT=3000 # je veux que mon Vite en développement écoute sur localhost:3000 (pour rester cohérent avec la prod)
                        # voila pourquoi j'ai ajouté VITE_PORT=3000 dans l’environnement mais on pouvait modifier directement mon package.json dans scripts : "dev": "vite --port 3000"
    command: npm run dev

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sitepro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:





















# version: '3.9'
# services:
#   db:
#     image: postgres:16
#     environment:
#       POSTGRES_DB: portfolio_db
#       POSTGRES_USER: portfolio_user
#       POSTGRES_PASSWORD: motdepassefort
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   backend:
#     build:
#       context: ./backend
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./backend:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       - DB_NAME=portfolio_db
#       - DB_USER=portfolio_user
#       - DB_PASSWORD=motdepassefort
#       - DB_HOST=db
#       - DB_PORT=5432

#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend

# volumes:
#   pgdata:
