
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sitepro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:





















# version: '3.9'
# services:
#   db:
#     image: postgres:16
#     environment:
#       POSTGRES_DB: portfolio_db
#       POSTGRES_USER: portfolio_user
#       POSTGRES_PASSWORD: motdepassefort
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   backend:
#     build:
#       context: ./backend
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./backend:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       - DB_NAME=portfolio_db
#       - DB_USER=portfolio_user
#       - DB_PASSWORD=motdepassefort
#       - DB_HOST=db
#       - DB_PORT=5432

#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend

# volumes:
#   pgdata:
