# pour un futur déploiement avec nginx et  gunicorn
version: '3.9'

services:
  db:
    image: postgres:16
    container_name: db_prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password_prod
      POSTGRES_DB: sitepro_prod
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod.backend
    container_name: backend_prod
    env_file:
      - ./backend/.env.prod
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: gunicorn site_pro.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod.frontend
    container_name: frontend_prod
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx_prod
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

volumes:
  pgdata_prod:
