services:
  - type: web
    name: bmc
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile  # adapte si nécessaire, chemin vers ton Dockerfile multi-étapes
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: ALLOWED_HOSTS
        value: bmc.onrender.com
      - key: POSTGRES_DB
        value: ${POSTGRES_DB}
      - key: POSTGRES_USER
        value: ${POSTGRES_USER}
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_PORT
        value: ${DB_PORT}
      - key: CLOUDINARY_CLOUD_NAME
        value: ${CLOUDINARY_CLOUD_NAME}
      - key: CLOUDINARY_API_KEY
        value: ${CLOUDINARY_API_KEY}
      - key: CLOUDINARY_API_SECRET
        value: ${CLOUDINARY_API_SECRET}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
    # Commande personnalisée pour lancer backend et nginx
    # Ici on lance Gunicorn en arrière-plan, puis nginx en avant-plan
    startCommand: >
      sh -c "gunicorn backend.site_pro.wsgi:application --bind 0.0.0.0:8000 & nginx -g 'daemon off;'"
