FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Collecte des fichiers statiques pour servir en prod
RUN python manage.py collectstatic --noinput

# Lancement avec Gunicorn (serveur WSGI pour Django)
CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]
